# Generated by Django 3.0.5 on 2021-05-05 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20210505_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 16, 28, 36, 632489)),
        ),
    ]
