# Generated by Django 3.0.5 on 2021-05-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_auto_20210508_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
