# Generated by Django 3.0.5 on 2021-05-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_auto_20210508_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_items',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
